exclude_paths:
  - "**/tests/"
  - "**/test/"
  - "docs/"
  - "coverage/"
  - "reports/"
  - "node_modules/"
  - "**/spec/"

ratings:
   paths:
   - "client/**/*.jsx"
   - "client/**/*.js"
   - "server/**/*.jsx"
   - "server/**/*.js"
   - "shared/**/*.js"

engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 100
