sudo: required
dist: trusty
language: node_js

node_js:
  - 6

services:
  - postgresql

before_script:
  - nvm install 6
  - npm install -g gulp
  - npm install
  - psql -c 'create database DMS_TEST;' -U postgres
  - NODE_ENV=test npm run db:migrate

script:
  - npm test
