export default {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  IS_SEARCH: 'IS_SEARCH',
  USER_HAS_NO_DOCUMENT: 'USER_HAS_NO_DOCUMENT',
  DISPLAY_DOCUMENTS: 'DISPLAY_DOCUMENTS',
  CREATE_NEW_DOCUMENT: 'CREATE_NEW_DOCUMENT',
  DELETE_DOCUMENT: 'DELETE_DOCUMENT',
  EDIT_DOCUMENT: 'EDIT_DOCUMENT',
  USER_LOGOUT: 'USER_LOGOUT',
  GET_ALL_ROLES: 'GET_ALL_ROLES',
  CREATE_NEW_ROLE: 'CREATE_NEW_ROLE',
  DELETE_ROLE: 'DELETE_ROLE',
  ADMIN_UPDATE_USER: 'ADMIN_UPDATE_USER',
  GET_ALL_USERS: 'GET_ALL_USERS',
  DELETE_USER: 'DELETE_USER',
  CREATE_NEW_USER: 'CREATE_NEW_USER'
};
